import { UserProfile, AdminStats, Oracle } from "./types";

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000);

export const MOCK_USERS: UserProfile[] = [
  {
    id: "u1",
    name: "오라클마스터",
    avatar: "🔮",
    role: "user",
    points: 124500,
    accuracy: 87,
    totalBets: 312,
    wonBets: 271,
    gradeId: "arceus",
    gradeOverride: false,
    joinedAt: daysAgo(180),
    lastActive: daysAgo(0),
    currentStreak: 6,
    bestStreak: 14,
    isBanned: false,
  },
  {
    id: "u2",
    name: "예언왕",
    avatar: "👑",
    role: "user",
    points: 98200,
    accuracy: 82,
    totalBets: 245,
    wonBets: 201,
    gradeId: "mewtwo",
    gradeOverride: false,
    joinedAt: daysAgo(120),
    lastActive: daysAgo(1),
    currentStreak: 3,
    bestStreak: 11,
    isBanned: false,
  },
  {
    id: "u3",
    name: "미래보기",
    avatar: "🎯",
    role: "user",
    points: 76300,
    accuracy: 79,
    totalBets: 189,
    wonBets: 149,
    gradeId: "mewtwo",
    gradeOverride: false,
    joinedAt: daysAgo(90),
    lastActive: daysAgo(0),
    currentStreak: 0,
    bestStreak: 9,
    isBanned: false,
  },
  {
    id: "u4",
    name: "크립토마스터",
    avatar: "🪙",
    role: "user",
    points: 65100,
    accuracy: 76,
    totalBets: 201,
    wonBets: 153,
    gradeId: "mewtwo",
    gradeOverride: true,
    joinedAt: daysAgo(60),
    lastActive: daysAgo(2),
    currentStreak: 2,
    bestStreak: 8,
    isBanned: false,
  },
  {
    id: "u5",
    name: "AI예언가",
    avatar: "🤖",
    role: "user",
    points: 52900,
    accuracy: 74,
    totalBets: 167,
    wonBets: 123,
    gradeId: "mew",
    gradeOverride: false,
    joinedAt: daysAgo(45),
    lastActive: daysAgo(0),
    currentStreak: 4,
    bestStreak: 7,
    isBanned: false,
  },
  {
    id: "u6",
    name: "불꽃예언자",
    avatar: "🔥",
    role: "user",
    points: 22800,
    accuracy: 68,
    totalBets: 89,
    wonBets: 61,
    gradeId: "growlithe",
    gradeOverride: false,
    joinedAt: daysAgo(30),
    lastActive: daysAgo(0),
    currentStreak: 0,
    bestStreak: 5,
    isBanned: false,
  },
  {
    id: "u7",
    name: "피카예언",
    avatar: "⚡",
    role: "user",
    points: 8900,
    accuracy: 61,
    totalBets: 54,
    wonBets: 33,
    gradeId: "pikachu",
    gradeOverride: false,
    joinedAt: daysAgo(20),
    lastActive: daysAgo(1),
    currentStreak: 1,
    bestStreak: 4,
    isBanned: false,
  },
  {
    id: "u8",
    name: "초보예언자",
    avatar: "🌱",
    role: "user",
    points: 2100,
    accuracy: 52,
    totalBets: 21,
    wonBets: 11,
    gradeId: "bulbasaur",
    gradeOverride: false,
    joinedAt: daysAgo(7),
    lastActive: daysAgo(0),
    currentStreak: 0,
    bestStreak: 2,
    isBanned: false,
  },
  {
    id: "u9",
    name: "스팸봇123",
    avatar: "🤖",
    role: "user",
    points: 500,
    accuracy: 12,
    totalBets: 8,
    wonBets: 1,
    gradeId: "magikarp",
    gradeOverride: false,
    joinedAt: daysAgo(3),
    lastActive: daysAgo(0),
    currentStreak: 0,
    bestStreak: 0,
    isBanned: true,
    banReason: "스팸 및 어뷰징 행위",
  },
  {
    id: "u10",
    name: "관리자",
    avatar: "🛡️",
    role: "admin",
    points: 999999,
    accuracy: 95,
    totalBets: 0,
    wonBets: 0,
    gradeId: "arceus",
    gradeOverride: true,
    joinedAt: daysAgo(365),
    lastActive: daysAgo(0),
    currentStreak: 0,
    bestStreak: 0,
    isBanned: false,
  },
];

export const ADMIN_STATS: AdminStats = {
  totalUsers: 12847,
  activeToday: 3241,
  totalOracles: 489,
  liveOracles: 23,
  totalBetsToday: 8923,
  totalPointsCirculating: 24_500_000,
  newUsersThisWeek: 342,
  avgAccuracy: 67,
};
