import { Oracle, Comment } from "./types";

/**
 * 각 예언의 commentCount 는 아래 MOCK_COMMENTS 의 해당 oracleId 댓글 수와
 * 반드시 일치해야 한다. (댓글을 추가/삭제하면 여기 숫자도 같이 고칠 것)
 */

const now = new Date();
const addHours = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000);
const addDays = (d: number) => new Date(now.getTime() + d * 24 * 60 * 60 * 1000);

export const MOCK_ORACLES: Oracle[] = [
  {
    id: "1",
    title: "삼성전자, 2026 Q2 실적이 전분기 대비 상승할까?",
    description: "글로벌 반도체 수요 회복과 HBM 수출 증가로 삼성전자의 2분기 실적 상승이 예상됩니다. 당신의 예언은?",
    category: "경제/주식",
    status: "live",
    options: [
      { id: "1a", label: "상승 📈", percentage: 67, totalBets: 1203, odds: 1.4 },
      { id: "1b", label: "하락 📉", percentage: 33, totalBets: 591, odds: 2.8 },
    ],
    totalParticipants: 1794,
    totalPool: 89700,
    endsAt: addDays(5),
    createdAt: addHours(-12),
    isHot: true,
    isTrending: true,
    isNew: false,
    tags: ["삼성전자", "반도체", "주식"],
    commentCount: 3,
    creatorName: "오라클킹",
    creatorAvatar: "👑",
  },
  {
    id: "2",
    title: "손흥민, 2026 월드컵 한국 대표팀 출전할까?",
    description: "무릎 부상 이후 컨디션 회복 중인 손흥민. 2026 월드컵 본선 무대를 밟을 수 있을까요?",
    category: "스포츠",
    status: "live",
    options: [
      { id: "2a", label: "출전 ⚽", percentage: 82, totalBets: 3401, odds: 1.2 },
      { id: "2b", label: "불출전 🚫", percentage: 18, totalBets: 748, odds: 5.2 },
    ],
    totalParticipants: 4149,
    totalPool: 207450,
    endsAt: addDays(3),
    createdAt: addHours(-2),
    isHot: true,
    isTrending: false,
    isNew: true,
    tags: ["손흥민", "월드컵", "축구"],
    commentCount: 3,
    creatorName: "축구예언자",
    creatorAvatar: "⚽",
  },
  {
    id: "3",
    title: "비트코인 2026년 내 10만 달러 돌파 유지할까?",
    description: "2025년 말 10만 달러를 돌파한 비트코인. 2026년 내내 그 수준을 유지할 수 있을지 예언해보세요.",
    category: "경제/주식",
    status: "live",
    options: [
      { id: "3a", label: "유지 🚀", percentage: 54, totalBets: 2891, odds: 1.7 },
      { id: "3b", label: "하락 💸", percentage: 46, totalBets: 2459, odds: 2.0 },
    ],
    totalParticipants: 5350,
    totalPool: 267500,
    endsAt: addDays(90),
    createdAt: addHours(-48),
    isHot: false,
    isTrending: true,
    isNew: false,
    tags: ["비트코인", "암호화폐", "투자"],
    commentCount: 2,
    creatorName: "크립토마스터",
    creatorAvatar: "🪙",
  },
  {
    id: "4",
    title: "내일 서울 기온이 20도 이상일까?",
    description: "봄이 왔다! 내일 서울의 최고기온이 20도를 넘을까요? 가장 쉬운 예언에 도전해보세요!",
    category: "날씨/자연",
    status: "live",
    options: [
      { id: "4a", label: "20도 이상 ☀️", percentage: 71, totalBets: 445, odds: 1.3 },
      { id: "4b", label: "20도 미만 🌥️", percentage: 29, totalBets: 182, odds: 3.2 },
    ],
    totalParticipants: 627,
    totalPool: 6270,
    endsAt: addHours(20),
    createdAt: addHours(-1),
    isHot: false,
    isTrending: false,
    isNew: true,
    tags: ["날씨", "서울", "봄"],
    commentCount: 2,
    creatorName: "기상예언자",
    creatorAvatar: "🌤️",
  },
  {
    id: "5",
    title: "GPT-5 출시일이 2026년 6월 이전일까?",
    description: "오픈AI의 차기 모델 GPT-5. 2026년 6월 이전에 공식 출시될 것이라는 루머가 무성한데, 당신의 예언은?",
    category: "기술/AI",
    status: "live",
    options: [
      { id: "5a", label: "6월 이전 출시 🤖", percentage: 43, totalBets: 1122, odds: 2.1 },
      { id: "5b", label: "6월 이후 출시 ⏳", percentage: 57, totalBets: 1489, odds: 1.6 },
    ],
    totalParticipants: 2611,
    totalPool: 130550,
    endsAt: addDays(60),
    createdAt: addHours(-24),
    isHot: false,
    isTrending: true,
    isNew: false,
    tags: ["GPT-5", "AI", "OpenAI"],
    commentCount: 3,
    creatorName: "AI예언가",
    creatorAvatar: "🤖",
  },
  {
    id: "6",
    title: "아이브 컴백 앨범 멜론 차트 1위 달성할까?",
    description: "하반기 컴백이 예고된 아이브. 신보 발매 후 멜론 실시간 차트 1위를 차지할 수 있을지 예언해주세요!",
    category: "엔터테인먼트",
    status: "upcoming",
    options: [
      { id: "6a", label: "1위 달성 🏆", percentage: 78, totalBets: 892, odds: 1.2 },
      { id: "6b", label: "1위 실패 😢", percentage: 22, totalBets: 251, odds: 4.3 },
    ],
    totalParticipants: 1143,
    totalPool: 57150,
    endsAt: addDays(45),
    createdAt: addHours(-6),
    isHot: false,
    isTrending: false,
    isNew: true,
    tags: ["아이브", "케이팝", "음원"],
    commentCount: 2,
    creatorName: "팝예언녀",
    creatorAvatar: "🎵",
  },
];

export const TRENDING_ORACLES = MOCK_ORACLES.filter((o) => o.isTrending);
export const HOT_ORACLES = MOCK_ORACLES.filter((o) => o.isHot);
export const NEW_ORACLES = MOCK_ORACLES.filter((o) => o.isNew);

export const MOCK_COMMENTS: Comment[] = [
  /* Oracle 1 — 삼성전자 */
  {
    id: "c1",
    oracleId: "1",
    author: "반도체왕",
    avatar: "💎",
    gradeId: "mewtwo",
    text: "HBM 수요만 봐도 상승 확실함. 단타 예언 완료!",
    likes: 45,
    likedByMe: false,
    createdAt: addHours(-3),
  },
  {
    id: "c2",
    oracleId: "1",
    author: "현실주의자",
    avatar: "🧐",
    gradeId: "growlithe",
    text: "중국 경쟁사 견제 때문에 쉽지 않다고 봄...",
    likes: 23,
    likedByMe: false,
    createdAt: addHours(-2),
  },
  {
    id: "c3",
    oracleId: "1",
    author: "오라클마스터",
    avatar: "🔮",
    gradeId: "arceus",
    text: "실적은 이미 컨센서스에 반영됐다고 봅니다. 신중하게 접근하세요.",
    likes: 67,
    likedByMe: false,
    createdAt: addHours(-1),
  },

  /* Oracle 2 — 손흥민 */
  {
    id: "c4",
    oracleId: "2",
    author: "축빠",
    avatar: "⚽",
    gradeId: "pikachu",
    text: "손흥민 없는 월드컵은 상상도 못함 무조건 출전!!",
    likes: 112,
    likedByMe: false,
    createdAt: addHours(-1),
  },
  {
    id: "c5",
    oracleId: "2",
    author: "미래보기",
    avatar: "🎯",
    gradeId: "mewtwo",
    text: "무릎 부상 회복 속도가 관건인데 최근 인터뷰 보면 긍정적입니다.",
    likes: 58,
    likedByMe: false,
    createdAt: addHours(-4),
  },
  {
    id: "c6",
    oracleId: "2",
    author: "초보예언자",
    avatar: "🌱",
    gradeId: "bulbasaur",
    text: "첫 예언 도전합니다! 출전에 걸었어요 🙏",
    likes: 9,
    likedByMe: false,
    createdAt: addHours(-0.5),
  },

  /* Oracle 3 — 비트코인 */
  {
    id: "c7",
    oracleId: "3",
    author: "크립토마스터",
    avatar: "🪙",
    gradeId: "mewtwo",
    text: "반감기 사이클 보면 2026년 내내 유지는 무리 없다고 봅니다.",
    likes: 88,
    likedByMe: false,
    createdAt: addHours(-6),
  },
  {
    id: "c8",
    oracleId: "3",
    author: "현실주의자",
    avatar: "🧐",
    gradeId: "growlithe",
    text: "규제 리스크를 너무 가볍게 보는 것 같은데요. 저는 하락 쪽.",
    likes: 34,
    likedByMe: false,
    createdAt: addHours(-2),
  },

  /* Oracle 4 — 서울 기온 */
  {
    id: "c9",
    oracleId: "4",
    author: "불꽃예언자",
    avatar: "🔥",
    gradeId: "growlithe",
    text: "기상청 예보만 봐도 답 나오는 문제 아닌가요 ㅋㅋ",
    likes: 21,
    likedByMe: false,
    createdAt: addHours(-0.5),
  },
  {
    id: "c10",
    oracleId: "4",
    author: "피카예언",
    avatar: "⚡",
    gradeId: "pikachu",
    text: "쉬운 예언으로 포인트 워밍업 하기 딱 좋네요 ⚡",
    likes: 14,
    likedByMe: false,
    createdAt: addHours(-0.2),
  },

  /* Oracle 5 — GPT-5 */
  {
    id: "c11",
    oracleId: "5",
    author: "AI예언가",
    avatar: "🤖",
    gradeId: "mew",
    text: "발표와 실제 출시는 다릅니다. 6월 이후에 걸었어요.",
    likes: 73,
    likedByMe: false,
    createdAt: addHours(-8),
  },
  {
    id: "c12",
    oracleId: "5",
    author: "오라클마스터",
    avatar: "🔮",
    gradeId: "arceus",
    text: "지난 세대들 출시 간격 평균 내보면 6월은 좀 이른 감이 있네요.",
    likes: 91,
    likedByMe: false,
    createdAt: addHours(-5),
  },
  {
    id: "c13",
    oracleId: "5",
    author: "초보예언자",
    avatar: "🌱",
    gradeId: "bulbasaur",
    text: "루머만 벌써 몇 번째인지... 이번엔 진짜였으면",
    likes: 18,
    likedByMe: false,
    createdAt: addHours(-1),
  },

  /* Oracle 6 — 아이브 */
  {
    id: "c14",
    oracleId: "6",
    author: "피카예언",
    avatar: "⚡",
    gradeId: "pikachu",
    text: "팬덤 화력 생각하면 1위는 거의 확정 아닐까요?",
    likes: 42,
    likedByMe: false,
    createdAt: addHours(-3),
  },
  {
    id: "c15",
    oracleId: "6",
    author: "미래보기",
    avatar: "🎯",
    gradeId: "mewtwo",
    text: "같은 주 컴백 라인업이 변수입니다. 생각보다 빡빡해요.",
    likes: 29,
    likedByMe: false,
    createdAt: addHours(-1),
  },
];

export const LEADERBOARD = [
  { rank: 1, name: "오라클마스터", avatar: "🔮", points: 124500, accuracy: 87 },
  { rank: 2, name: "예언왕", avatar: "👑", points: 98200, accuracy: 82 },
  { rank: 3, name: "미래보기", avatar: "🎯", points: 76300, accuracy: 79 },
  { rank: 4, name: "크립토마스터", avatar: "🪙", points: 65100, accuracy: 76 },
  { rank: 5, name: "AI예언가", avatar: "🤖", points: 52900, accuracy: 74 },
];
